services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB_NAME: book_social_network
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - postgres: /data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local